import React, { useState, useEffect } from 'react';
import { avatarService } from '../../services/avatarService';
import HelmetImageEditor from './HelmetImageEditor';

interface AvatarImageProps {
  userId: string;
  username: string;
  size?: number;
  className?: string;
}

const AvatarImage: React.FC<AvatarImageProps> = ({ 
  userId, 
  username, 
  size = 48,
  className = '' 
}) => {
  const [avatarData, setAvatarData] = useState<any>(null);
  const [customImageUrl, setCustomImageUrl] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    loadAvatarData();
  }, [userId]);

  const loadAvatarData = async () => {
    try {
      setLoading(true);
      setError(null);

      // Get user's avatar configuration
      const response = await avatarService.getUserAvatar(userId);
      setAvatarData(response.avatar);

      // If user has a customized avatar, generate the image
      if (response.avatar.isCustomized && response.avatar.helmetTemplateId) {
        // The image will be generated by the HelmetImageEditor component
        setLoading(false);
      } else {
        // Use default avatar
        setLoading(false);
      }
    } catch (err) {
      console.error('Error loading avatar data:', err);
      setError('Failed to load avatar');
      setLoading(false);
    }
  };

  const handleImageGenerated = (dataUrl: string) => {
    setCustomImageUrl(dataUrl);
  };

  if (loading) {
    return (
      <div 
        className={`bg-gray-300 rounded-lg flex items-center justify-center ${className}`}
        style={{ width: size, height: size * 0.8 }}
      >
        <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-gray-600"></div>
      </div>
    );
  }

  if (error) {
    return (
      <div 
        className={`bg-red-100 border border-red-400 text-red-700 rounded-lg flex items-center justify-center text-xs ${className}`}
        style={{ width: size, height: size * 0.8 }}
      >
        Error
      </div>
    );
  }

  // If user has a customized avatar, show the image editor
  if (avatarData?.isCustomized && avatarData?.helmetTemplateId) {
    return (
      <div className={`inline-block ${className}`}>
        <HelmetImageEditor
          helmetTemplateId={avatarData.helmetTemplateId}
          helmetColors={avatarData.helmetColors}
          helmetNumber={avatarData.helmetNumber}
          size={size}
          onImageGenerated={handleImageGenerated}
        />
      </div>
    );
  }

  // Default avatar (grey helmet with dash)
  return (
    <div 
      className={`bg-gray-400 rounded-lg flex items-center justify-center ${className}`}
      style={{ width: size, height: size * 0.8 }}
    >
      <span className="text-white font-bold text-xs">-</span>
    </div>
  );
};

export default AvatarImage; 